### ISSUE TITLE
Why all inputs are required by default ?

### ISSUE THREAD

**Issue by jbanety** [ezekielaquino/SimpleValidate#1]
Your simple lib is very great but I can't understand why you consider inputs are required by default.

Wa have the HTML5 attribute `required` to ensure required inputs to be checked.

So the logic can be inverted. ?

**Comment by ezekielaquino** [comment]
You are absolutely right @jbanety– it was a change done in haste :-) I think it is better inverted: ignored if `input.hasAttribute('required')`

Thank you for the feedback and feel free to do pull request(s) 👍

**Comment by ezekielaquino** [comment]
Thanks @jbanety. Included this change in 6a5a5ac
